# 2. Build Next.js app
FROM node:20-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID

# Public Variables
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID

# ADD THESE (server envs required during build)
ARG PLATFORM_DEVELOPER_PASSWORD
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_PRICE_ID_TIER_A
ARG STRIPE_PRICE_ID_TIER_B
ARG STRIPE_PRICE_ID_TIER_C
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV PLATFORM_DEVELOPER_PASSWORD=$PLATFORM_DEVELOPER_PASSWORD
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV STRIPE_PRICE_ID_TIER_A=$STRIPE_PRICE_ID_TIER_A
ENV STRIPE_PRICE_ID_TIER_B=$STRIPE_PRICE_ID_TIER_B
ENV STRIPE_PRICE_ID_TIER_C=$STRIPE_PRICE_ID_TIER_C
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Uses your .env.local inside the image at build time///
RUN npm run build

# 3. Production runtime
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=development


# ENV PORT=3000
# # # optional non root user
# # RUN useradd -m nextjs
# # USER nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "run", "start"]
