import type { Timestamp } from "firebase/firestore";
import type { HostBillingTier } from "./club";

export type OnboardingRole = "host" | "member";

export interface OnboardingClubDraft {
  name?: string;
  description?: string;
  slug?: string;
  clubId?: string;
  autoGeneratedName?: boolean;
  billingTier?: HostBillingTier;
  lastUpdatedAt?: Timestamp | string;
}

export interface OnboardingProgressMeta {
  currentStep?: string;
  startedAt?: Timestamp | string;
  lastStepCompletedAt?: Timestamp | string;
}

export interface OnboardingHostStatus {
  activated?: boolean;
  clubId?: string;
  billingTier?: HostBillingTier;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  upgradeScheduledFor?: Timestamp | string;
  downgradeEligibleAfter?: Timestamp | string;
  pendingActivation?: boolean;
}

export interface OnboardingState {
  role?: OnboardingRole;
  clubDraft?: OnboardingClubDraft;
  progress?: OnboardingProgressMeta;
  hostStatus?: OnboardingHostStatus;
  completedAt?: Timestamp | string;
  lastCompletedFlow?: OnboardingRole;
}

